### ISSUE TITLE
The bug report title

### ISSUE THREAD

**Issue by kaskadz** [relativitydev/relativity.testing.framework#126]
### Describe the bug

Relativity platform documentation tab for RTF returns 404: https://platform.relativity.com/RelativityOne/#https://relativitydev.github.io/relativity.testing.framework/articles/What-Is-RTF.html
![image](https://user-images.githubusercontent.com/31192049/144582732-ec6cd8ba-bc12-47f2-a295-0c1f7c82f3ad.png)

### Steps to Reproduce

Enter this page: https://platform.relativity.com/RelativityOne/#https://relativitydev.github.io/relativity.testing.framework/articles/What-Is-RTF.html

### Relativity.Testing.Framework Version

n/a

### Relativity.Testing.Framework.API Version

n/a

### Relativity environment installation Type

RelativityOne

### Environment version

n/a

### Expected Behavior

The documentation page should appear or at least no 404 error should be visible

### Actual Behavior

404 page appears

### Screenshots

Provided in the description

### Additional Context

Spotted on Dec 3rd 2021 at 09:56:16 UTC

**Comment by paulletang** [comment]
Hey @kaskadz,

The page that you're looking for can be found [here](https://relativitydev.github.io/relativity.testing.framework/articles/What-Is-RTF.html).

The link that you used to get here is owned by Platform/Documentation.
I wasn't even aware that they had a link to our documentation.

I'll bring this to their attention.

Thanks for reporting this!

**Comment by Nmaa75** [comment]
Thank you for the note about the broken link. This has been fixed in the product documentation, and will show up after tonight’s scheduled build of the platform documentation.
